### ISSUE TITLE
Find file in project very slow

### ISSUE THREAD

**Issue by jhirn** [defunkt/textmate.el#16]
Hello. I've been plagued by this problem for a while now. Using the textmate mode find file in project will spike my CPU to 100% and take several (20-30) seconds to complete during which emacs is completely frozen. I'm not sure if I am causing this problem but it has been consistant across every machine I've used it with including OSX, Win7, Ubuntu and RHEL. I wish I had more to add on why this is happening but I can't seem to figure out what is causing this pause. 

Please let me know if there is something I can do to provide more information. I have potential emacs converts who would love to use this feature. Thanks!

**Comment by defunkt** [comment]
It's slow for me, too. Driving me bonkers.

**Comment by mbriggs** [comment]
bring this in https://github.com/scottjad/ido-hacks, add it to the load path, and do (ido-hacks 1). My project at work has enough files that the ido completion would lock up emacs for almost 30s each keystroke on textmate-goto-project-file. with ido-hacks, it is instant

**Comment by evanlong** [comment]
I made some progress on this issue with: https://github.com/defunkt/textmate.el/pull/21

**Comment by rosewd1954** [comment]
Thanks for accepting me. let me introduce my self to you,Am Mrs Delane Franco, A christian 58 years old,I have a donation to donate,Am a widow from manila phillipine, Recently my Doctor told me that I would not last for the next five months due to cancer problem. i decided to donate this fund to an organization or good person that will utilize this money the way I am going to instruct herein. Meanwhile I am not afraid of death hence I know where I am going. Whoever that Wants to serve the Lord must serve him in truth and faith, "serving him with all you have, knowing that naked we come and naked we must go" Contact me on the this email address (francodelane AT outlook.fr) and any delay in your reply will give me room in sourcing another good person, organization for this same purpose. Please assure me that you will act accordingly as I Stated herein. Remain bless in the lord. Your Sister in christ . Delane Franco

**Comment by ElRealRondon** [comment]
- _**@`

1. 

`**_

**Comment by ElRealRondon** [comment]
Xccjrijt

**Comment by ElRealRondon** [comment]
- [ ] 

- ### @timcharper

**Comment by ElRealRondon** [comment]
> Hello. I've been plagued by this problem for a while now. Using the textmate mode find file in project will spike my CPU to 100% and take several (20-30) seconds to complete during which emacs is completely frozen. I'm not sure if I am causing this problem but it has been consistant across every machine I've used it with including OSX, Win7, Ubuntu and RHEL. I wish I had more to add on why this is happening but I can't seem to figure out what is causing this pause.
> 
> Please let me know if there is something I can do to provide more information. I have potential emacs converts who would love to use this feature. Thanks!
